version: '3'

services:
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root      
    networks:
      - nodenet

  hellonode:
    build: 
      context: ./node      
    image: mikaelmedeiros/hello-node
    container_name: hellonode
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodenet
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx        
    image: mikaelmedeiros/nginx
    container_name: nginx
    tty: true
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - hellonode

networks:
  nodenet:
    driver: bridge
